CREATE TABLE funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    ramal VARCHAR(10) NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE sala (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    capacidade INTEGER NOT NULL,
    localizacao VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT chk_sala_capacidade
        CHECK (capacidade > 0),

    CONSTRAINT chk_sala_status
        CHECK (status IN ('ATIVA', 'INATIVA'))
);

CREATE TABLE reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT NOT NULL,
    sala_id BIGINT NOT NULL,
    data DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    status VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_reserva_funcionario
        FOREIGN KEY (funcionario_id)
        REFERENCES funcionario(id),

    CONSTRAINT fk_reserva_sala
        FOREIGN KEY (sala_id)
        REFERENCES sala(id),

    CONSTRAINT chk_reserva_horario
        CHECK (hora_inicio < hora_fim),

    CONSTRAINT chk_reserva_status
        CHECK (status IN ('AGENDADA', 'CANCELADA'))
);

CREATE INDEX idx_reserva_funcionario_id
    ON reserva(funcionario_id);

CREATE INDEX idx_reserva_sala_id
    ON reserva(sala_id);

CREATE INDEX idx_reserva_sala_data_status
    ON reserva(sala_id, data, status);
